### ISSUE TITLE
博弈论,SG函数和Nim游戏|笔记 | BeautyYu言醴的Blog

### ISSUE THREAD

**Issue by BeautyyuYanli** [BeautyyuYanli/blog-gitalk#4]
https://beautyyuyanli.ml/2018/10/16/2018-10-16-%E5%8D%9A%E5%BC%88%E8%AE%BA,SG%E5%87%BD%E6%95%B0%E5%92%8CNim%E6%B8%B8%E6%88%8F%E7%AC%94%E8%AE%B0/ 

 Beautyyu言醴的个人独立博客

**Comment by BeautyyuYanli** [comment]
QAQ

**Comment by BeautyyuYanli** [comment]
gitalk真姬儿愉快

**Comment by Chilkings** [comment]
SG:设状态y是当前状态x的后继状态,显然y可以是任何小于x的非负整数.根据SG函数的定义,我们发现SG(x)=x
这里小于应该得改成大于吧

**Comment by BeautyyuYanli** [comment]
> @Chilkings
> SG:设状态y是当前状态x的后继状态,显然y可以是任何小于x的非负整数.根据SG函数的定义,我们发现SG(x)=x
> 这里小于应该得改成大于吧

不是哦. 因为一堆中现在有x个石子, 随意取若干个后变为y个, y<=x. 从状态x转移到状态y, y是x的后继状态
